# See https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: main

# See https://www.netlifycms.org/docs/configuration-options/#locale
locale: de

# See https://www.netlifycms.org/docs/configuration-options/#display-url
display_url: https://gatsby-netlifycms.tortuga-webdesign.de 

# See https://www.netlifycms.org/docs/configuration-options/#site-url
site_url: https://gatsby-netlifycms.tortuga-webdesign.de 

# See https://www.netlifycms.org/docs/configuration-options/#media-folder
media_folder: content/media

# See https://www.netlifycms.org/docs/collection-types/
collections:
  - name: 'pages'
    label: Seite
    delete: false
    editor:
      preview: true
    files:
      - file: 'content/pages/contact.md'
        label: Kontakt
        name: 'contact-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ContactPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'contact' }
          - { label: Title, name: title, widget: string }
          - {
              label: Featured Image,
              name: featuredImage,
              widget: image,
              options:
                { media_library: { config: { imageShrink: 2600x2600 } } },
            }
          - { label: Subtitle, name: subtitle, widget: markdown }
          - { label: Body, name: body, widget: markdown }
          - { label: Address, name: address, widget: text }
          - { label: Phone, name: phone, widget: string }
          - { label: Email Address, name: email, widget: string }
          - name: locations
            label: locations
            widget: list
            fields:
              - {
                  name: mapLink,
                  label: mapLink,
                  widget: string,
                  required: false,
                  default: '',
                }
              - {
                  name: lat,
                  label: latitude,
                  widget: string,
                  required: false,
                  delete: false,
                  default: '',
                }
              - {
                  name: lng,
                  label: longitude,
                  widget: string,
                  required: false,
                  delete: false,
                  default: '',
                }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

      - file: 'content/pages/blog.md'
        label: Blog
        name: 'blog-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: BlogIndex,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'blog' }
          - { label: Title, name: title, widget: string }
          - { label: Featured Image, name: featuredImage, widget: image }
          - { label: Subtitle, name: subtitle, widget: markdown }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }
      - file: 'content/pages/home.md'
        label: Startseite
        name: 'home-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Title, name: title, widget: string }
          - { label: Featured Image, name: featuredImage, widget: image }
          - { label: Subtitle, name: subtitle, widget: markdown, required: false }
          - { label: Body, name: body, widget: markdown }
          - label: 'Accordion'
            name: 'accordion'
            widget: 'list'
            required: false
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: Content, name: content, widget: text }
          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

  - name: animals
    label: Wildtier
    editor:
      preview: true
    folder: content/animals
    slug: '{{slug}}'
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: SinglePost }
      - { label: Titel, name: title, widget: string }
      - {
          label: Bild,
          name: featuredImage,
          widget: image,
          required: false,
        }
      - { label: Auszug, name: excerpt, widget: text }
      - { label: Inhalt, name: body, widget: markdown }
      - label: 'Kategorie'
        name: 'category'
        widget: 'relation'
        collection: 'categories'
        searchFields: ['title']
        valueField: 'title'
      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Titel, name: title, widget: string, required: false }
          - {
              label: Beschreibung,
              name: description,
              widget: text,
              required: false,
            }

  - name: categories
    label: Kategorie
    editor:
      preview: false
    folder: content/categories
    slug: '{{slug}}'
    create: true
    fields:
      - { label: Titel, name: title, widget: string }
      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Titel, name: title, widget: string, required: false }
          - {
              label: Beschreibung,
              name: description,
              widget: text,
              required: false,
            }

  - name: 'settings'
    label: Einstellungen
    delete: false
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: Global
        name: 'global-settings'
        fields:
          - { label: Titel der Seite, name: siteTitle, widget: string }
          - { label: URL der Seite, name: siteUrl, widget: string, required: false }
          - {
              label: Beschreibung der Seite,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Bild für Verlinkung in Sozialen Medien
            name: socialMediaCard
            widget: image
          - {
              label: Google Analytics Tracking ID,
              name: googleTrackingId,
              widget: string,
              required: false,
            }
